global:
  resolve_timeout: 1m
  #slack_api_url: 'https://hooks.slack.com/services/SECRET/B01SQDAUU7L/SECRET'


route:
  group_by: [Alertname]
  #receiver: 'slack-notifications'
  receiver: 'email'

receivers:
# - name: 'slack-notifications'
#   slack_configs:
#   - channel: '#dima_parshyn'
#     send_resolved: true
- name: 'email'
  email_configs:
  - to: 'mail_to@gmail.com'
    from: 'mail_from@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'mail_from@gmail.com'
    auth_identity: 'mail_from@gmail.com'
    auth_password: 'password'
