version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    #build: ../../src/ui
    image: ${USER_NAME}/ui:${UI_TAG}
    ports:
      - ${HOST_PORT}:${CONT_PORT}/tcp
    networks:
      - front_net

  post:
    #build: ../../src/post-py
    image: ${USER_NAME}/post:${POST_TAG}
    networks:
      - front_net
      - back_net

  comment:
    #build: ../../src/comment
    image: ${USER_NAME}/comment:${COMMENT_TAG}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: ${BACK_SUBNET}
  front_net:
    ipam:
      config:
        - subnet: ${FRONT_SUBNET}
